language: csharp

os: linux
dist: trusty
sudo: required
dotnet: 2.1.402

before_install:
  - curl -sL https://github.com/annymsMthd/gogitver/releases/download/0.5.1/linux.tar.gz | tar zx

script:
  - dotnet restore || travis_terminate 1
  - dotnet test --no-restore tests/Syncromatics.Configuration.Validation.UnitTests || travis_terminate 1
  - dotnet pack --no-restore src/Syncromatics.Configuration.Validation --configuration Release /p:Version=$(./gogitver) || travis_terminate 1;
  - dotnet nuget push src/Syncromatics.Configuration.Validation/bin/Release/*.nupkg -s https://www.nuget.org/api/v2/package -k $NUGET_API_KEY || travis_terminate 1;